// Canonical 66-book Protestant order, independent of any single translation.
// abbrev is used in compact UI (tab titles, breadcrumbs).
module.exports = [
  ['Genesis', 'Gen', 'OT'], ['Exodus', 'Exo', 'OT'], ['Leviticus', 'Lev', 'OT'],
  ['Numbers', 'Num', 'OT'], ['Deuteronomy', 'Deut', 'OT'], ['Joshua', 'Josh', 'OT'],
  ['Judges', 'Judg', 'OT'], ['Ruth', 'Ruth', 'OT'], ['1 Samuel', '1Sam', 'OT'],
  ['2 Samuel', '2Sam', 'OT'], ['1 Kings', '1Kgs', 'OT'], ['2 Kings', '2Kgs', 'OT'],
  ['1 Chronicles', '1Chr', 'OT'], ['2 Chronicles', '2Chr', 'OT'], ['Ezra', 'Ezra', 'OT'],
  ['Nehemiah', 'Neh', 'OT'], ['Esther', 'Esth', 'OT'], ['Job', 'Job', 'OT'],
  ['Psalms', 'Psa', 'OT'], ['Proverbs', 'Prov', 'OT'], ['Ecclesiastes', 'Eccl', 'OT'],
  ['Song of Solomon', 'Song', 'OT'], ['Isaiah', 'Isa', 'OT'], ['Jeremiah', 'Jer', 'OT'],
  ['Lamentations', 'Lam', 'OT'], ['Ezekiel', 'Ezek', 'OT'], ['Daniel', 'Dan', 'OT'],
  ['Hosea', 'Hos', 'OT'], ['Joel', 'Joel', 'OT'], ['Amos', 'Amos', 'OT'],
  ['Obadiah', 'Obad', 'OT'], ['Jonah', 'Jonah', 'OT'], ['Micah', 'Mic', 'OT'],
  ['Nahum', 'Nah', 'OT'], ['Habakkuk', 'Hab', 'OT'], ['Zephaniah', 'Zeph', 'OT'],
  ['Haggai', 'Hag', 'OT'], ['Zechariah', 'Zech', 'OT'], ['Malachi', 'Mal', 'OT'],
  ['Matthew', 'Matt', 'NT'], ['Mark', 'Mark', 'NT'], ['Luke', 'Luke', 'NT'],
  ['John', 'John', 'NT'], ['Acts', 'Acts', 'NT'], ['Romans', 'Rom', 'NT'],
  ['1 Corinthians', '1Cor', 'NT'], ['2 Corinthians', '2Cor', 'NT'], ['Galatians', 'Gal', 'NT'],
  ['Ephesians', 'Eph', 'NT'], ['Philippians', 'Phil', 'NT'], ['Colossians', 'Col', 'NT'],
  ['1 Thessalonians', '1Th', 'NT'], ['2 Thessalonians', '2Th', 'NT'], ['1 Timothy', '1Tim', 'NT'],
  ['2 Timothy', '2Tim', 'NT'], ['Titus', 'Titus', 'NT'], ['Philemon', 'Phlm', 'NT'],
  ['Hebrews', 'Heb', 'NT'], ['James', 'Jas', 'NT'], ['1 Peter', '1Pet', 'NT'],
  ['2 Peter', '2Pet', 'NT'], ['1 John', '1Jn', 'NT'], ['2 John', '2Jn', 'NT'],
  ['3 John', '3Jn', 'NT'], ['Jude', 'Jude', 'NT'], ['Revelation', 'Rev', 'NT'],
].map(([name, abbrev, testament], i) => ({ ordinal: i + 1, name, abbrev, testament }));
